# 这个文件告诉 Netlify 如何处理请求

# 定义一个“重写”规则
[[redirects]]
  # 当访问的路径是 /proxy/ 开头的任何地址时...
  from = "/proxy/*"
  
  # ...不要改变浏览器地址，而是内部把请求交给名为 "proxy" 的函数处理
  to = "/.netlify/functions/proxy"
  
  # 状态码 200 表示这是一个“重写”，而不是一个“跳转”
  status = 200
